language: python
python: 3.6
install: pip install .
script: skip
before_deploy:
  - echo "$TRAVIS_TAG" > VERSION
deploy:
  on:
    repo: cenkalti/putio.py
    tags: true
  skip_cleanup: true
  provider: pypi
  user: cenkalti
  password:
    secure: hs3Z5MI7iVceUIXKIF6CzGcawKRRwuSoqcDh28sJBW9CrXtcWNzG+fTB/wsSgdvCv8EBtAWLzT9TCCmtYBKOYRKPWsjTWv7JqRhz8mcJ8Wqc5GjKPeST24TI44qEPgJG5uVhxdkiQ852QKspNir6ACin8pL9Zh5opw5AiUA4sBQ=
