language: python
python: 3.6
install: pip install .
script: pytest
before_deploy:
  - echo "$TRAVIS_TAG" > VERSION
deploy:
  on:
    repo: cenkalti/putio.py
    tags: true
  skip_cleanup: true
  provider: pypi
  user: cenkalti
  password:
    secure: WISXo+4rni+S51yz6YBiv+Nee8L+GEWb10chnAOkqobnk4IV8p87fyH6hlD5WwzdRUJmvnmvgLm8xni0vfGmQOAwfyCFdDMWdXubL74SRLjG0g7cKWzS8GumlgA+1m2tHDYv2fIFOjgrF7KKX3GXhFUlv8ei7RyYd8+ecLV6L/Y=
